# Generated by Django 4.1.4 on 2022-12-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_anysign_demo', '0002_auto_20160705_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturetype',
            name='signature_backend_code',
            field=models.CharField(choices=[], db_index=True, max_length=50, verbose_name='signature backend'),
        ),
    ]
